Add Dockerfile
flipdot/spaceapi pull request #1
Opened 2020-08-04 21:34 UTC by 0boro

2020-08-05 10:38 UTC, rbnis reviewed
See comments

2020-08-05 10:38 UTC, rbnis commented on docker-compose.yml
> +        - "traefik.http.routers.spaceapi.rule=Host(`spaceapi.flipdot.dev`)"
For prod the host should be `api.flipdot.org`.

2020-08-05 10:38 UTC, rbnis commented on deploytoswarm.yml
> +        version: Add_dockerfile
This only works for this pull request.
With the next PR the default branch should be used.

2020-08-13 09:00 UTC, cfstras requested changes

2020-08-13 09:00 UTC, cfstras commented on deploytoswarm.yml
> +        username: "test_flipdot_test"
should the username not also be an ENV?

2020-08-13 09:00 UTC, cfstras commented on docker-compose.yml
> +        - "traefik.http.routers.spaceapi.tls.certresolver=myresolver"
what's `myresolver` and where is it defined?

2020-10-07 14:33 UTC, cfstras commented on deployment/docker-compose.yml
> +      - "traefik.http.routers.spaceapi.rule=Host(`api.${base_domain}`)"
maybe "api" should also be a variable?

2020-10-07 14:33 UTC, cfstras approved these changes

2020-10-27 21:04 UTC, merged